import type { AppRole, Role } from "../types";

export const VALID_APP_ROLES = ["administrator", "standard"] as const;
export const VALID_PROJECT_ROLES = ["owner", "editor", "coder", "viewer"] as const;

export const PERMISSIONS = [
  "viewProject",
  "viewProjectDashboard",
  "viewProjectMetadata",
  "editProjectMetadata",
  "deleteProject",
  "exportProject",
  "restoreProjectBackup",
  "viewProjectUsers",
  "inviteProjectUsers",
  "removeProjectUsers",
  "changeProjectRoles",
  "transferProjectOwnership",
  "viewDocuments",
  "openDocumentDetails",
  "createDocument",
  "uploadDocument",
  "batchUploadDocuments",
  "importSpreadsheetDocuments",
  "editDocumentMetadata",
  "editDocumentContent",
  "deleteDocument",
  "associateDocumentsWithCases",
  "viewDocumentAttributes",
  "editDocumentAttributes",
  "createDocumentAttributes",
  "deleteDocumentAttributes",
  "viewCases",
  "openCaseDetails",
  "createCase",
  "editCase",
  "deleteCase",
  "linkCaseDocuments",
  "unlinkCaseDocuments",
  "viewCaseAttributes",
  "editCaseAttributes",
  "createCaseAttributes",
  "deleteCaseAttributes",
  "viewCodebook",
  "createCode",
  "editCode",
  "deleteCode",
  "reorganizeCodes",
  "viewCodeDetails",
  "manageCodeAttributes",
  "viewAnnotations",
  "createAnnotations",
  "editAnnotationNotes",
  "deleteAnnotations",
  "recodeAnnotations",
  "bulkCodeAnnotations",
  "viewUncodedText",
  "filterAnnotations",
  "viewMemos",
  "createMemo",
  "editMemo",
  "deleteMemo",
  "associateMemoObjects",
  "viewReports",
  "createReports",
  "editReportConfiguration",
  "deleteReports",
  "exportReports",
  "viewAiAssistHome",
  "viewAiAssistTools",
  "enableProjectAiAssist",
  "buildEmbeddings",
  "deleteEmbeddings",
  "useAiChat",
  "useAiCodingTools",
  "useAiAttributeTools",
  "useAiAnalyzeTools",
  "useAiProcessDocuments",
  "saveAiOutputs",
  "editAiOutputs",
  "exportAiOutputsToProject",
  "deleteAiOutputs",
  "reviewProcessedDocuments",
  "approveProcessedDocuments",
  "openAppSettings",
  "changeStartupSettings",
  "manageLlmSettings",
  "downloadEmbeddingModel",
  "deleteEmbeddingModel",
  "viewLocalUsers",
  "deleteLocalUsers",
  "clearLocalAppData",
  "viewLicensingInfo",
  "bypassReadOnlyProtections",
  "performPermanentDeleteActions",
  "exportSensitiveContent",
  "manageBackupsAndRestores",
] as const;

export type Permission = typeof PERMISSIONS[number];

type ProjectRolePermissionMap = Record<Role, readonly Permission[]>;
type AppRolePermissionMap = Record<AppRole, readonly Permission[]>;

const PROJECT_ROLE_PERMISSIONS: ProjectRolePermissionMap = {
  owner: [
    "viewProject",
    "viewProjectDashboard",
    "viewProjectMetadata",
    "editProjectMetadata",
    "deleteProject",
    "exportProject",
    "restoreProjectBackup",
    "viewProjectUsers",
    "inviteProjectUsers",
    "removeProjectUsers",
    "changeProjectRoles",
    "transferProjectOwnership",
    "viewDocuments",
    "openDocumentDetails",
    "createDocument",
    "uploadDocument",
    "batchUploadDocuments",
    "importSpreadsheetDocuments",
    "editDocumentMetadata",
    "editDocumentContent",
    "deleteDocument",
    "associateDocumentsWithCases",
    "viewDocumentAttributes",
    "editDocumentAttributes",
    "createDocumentAttributes",
    "deleteDocumentAttributes",
    "viewCases",
    "openCaseDetails",
    "createCase",
    "editCase",
    "deleteCase",
    "linkCaseDocuments",
    "unlinkCaseDocuments",
    "viewCaseAttributes",
    "editCaseAttributes",
    "createCaseAttributes",
    "deleteCaseAttributes",
    "viewCodebook",
    "createCode",
    "editCode",
    "deleteCode",
    "reorganizeCodes",
    "viewCodeDetails",
    "manageCodeAttributes",
    "viewAnnotations",
    "createAnnotations",
    "editAnnotationNotes",
    "deleteAnnotations",
    "recodeAnnotations",
    "bulkCodeAnnotations",
    "viewUncodedText",
    "filterAnnotations",
    "viewMemos",
    "createMemo",
    "editMemo",
    "deleteMemo",
    "associateMemoObjects",
    "viewReports",
    "createReports",
    "editReportConfiguration",
    "deleteReports",
    "exportReports",
    "viewAiAssistHome",
    "viewAiAssistTools",
    "enableProjectAiAssist",
    "buildEmbeddings",
    "deleteEmbeddings",
    "useAiChat",
    "useAiCodingTools",
    "useAiAttributeTools",
    "useAiAnalyzeTools",
    "useAiProcessDocuments",
    "saveAiOutputs",
    "editAiOutputs",
    "exportAiOutputsToProject",
    "deleteAiOutputs",
    "reviewProcessedDocuments",
    "approveProcessedDocuments",
    "openAppSettings",
    "viewLicensingInfo",
    "bypassReadOnlyProtections",
    "performPermanentDeleteActions",
    "exportSensitiveContent",
    "manageBackupsAndRestores",
  ],
  editor: [
    "viewProject",
    "viewProjectDashboard",
    "viewProjectMetadata",
    "editProjectMetadata",
    "exportProject",
    "viewProjectUsers",
    "inviteProjectUsers",
    "viewDocuments",
    "openDocumentDetails",
    "createDocument",
    "uploadDocument",
    "batchUploadDocuments",
    "importSpreadsheetDocuments",
    "editDocumentMetadata",
    "editDocumentContent",
    "deleteDocument",
    "associateDocumentsWithCases",
    "viewDocumentAttributes",
    "editDocumentAttributes",
    "createDocumentAttributes",
    "viewCases",
    "openCaseDetails",
    "createCase",
    "editCase",
    "deleteCase",
    "linkCaseDocuments",
    "unlinkCaseDocuments",
    "viewCaseAttributes",
    "editCaseAttributes",
    "createCaseAttributes",
    "viewCodebook",
    "createCode",
    "editCode",
    "deleteCode",
    "reorganizeCodes",
    "viewCodeDetails",
    "manageCodeAttributes",
    "viewAnnotations",
    "createAnnotations",
    "editAnnotationNotes",
    "deleteAnnotations",
    "recodeAnnotations",
    "bulkCodeAnnotations",
    "viewUncodedText",
    "filterAnnotations",
    "viewMemos",
    "createMemo",
    "editMemo",
    "deleteMemo",
    "associateMemoObjects",
    "viewReports",
    "createReports",
    "editReportConfiguration",
    "deleteReports",
    "exportReports",
    "viewAiAssistHome",
    "viewAiAssistTools",
    "enableProjectAiAssist",
    "buildEmbeddings",
    "deleteEmbeddings",
    "useAiChat",
    "useAiCodingTools",
    "useAiAttributeTools",
    "useAiAnalyzeTools",
    "useAiProcessDocuments",
    "saveAiOutputs",
    "editAiOutputs",
    "exportAiOutputsToProject",
    "deleteAiOutputs",
    "reviewProcessedDocuments",
    "approveProcessedDocuments",
    "openAppSettings",
    "viewLicensingInfo",
    "performPermanentDeleteActions",
    "exportSensitiveContent",
  ],
  coder: [
    "viewProject",
    "viewProjectDashboard",
    "viewProjectMetadata",
    "viewProjectUsers",
    "viewDocuments",
    "openDocumentDetails",
    "viewDocumentAttributes",
    "viewCases",
    "openCaseDetails",
    "viewCaseAttributes",
    "viewCodebook",
    "viewCodeDetails",
    "viewAnnotations",
    "createAnnotations",
    "editAnnotationNotes",
    "deleteAnnotations",
    "recodeAnnotations",
    "viewUncodedText",
    "filterAnnotations",
    "viewMemos",
    "createMemo",
    "editMemo",
    "associateMemoObjects",
    "viewReports",
    "createReports",
    "editReportConfiguration",
    "exportReports",
    "viewAiAssistHome",
    "viewAiAssistTools",
    "useAiChat",
    "useAiCodingTools",
    "useAiAttributeTools",
    "useAiAnalyzeTools",
    "saveAiOutputs",
    "editAiOutputs",
    "reviewProcessedDocuments",
    "openAppSettings",
    "viewLicensingInfo",
    "exportSensitiveContent",
  ],
  viewer: [
    "viewProject",
    "viewProjectDashboard",
    "viewProjectMetadata",
    "viewProjectUsers",
    "viewDocuments",
    "openDocumentDetails",
    "viewDocumentAttributes",
    "viewCases",
    "openCaseDetails",
    "viewCaseAttributes",
    "viewCodebook",
    "viewCodeDetails",
    "viewAnnotations",
    "viewUncodedText",
    "filterAnnotations",
    "viewMemos",
    "viewReports",
    "viewAiAssistHome",
    "viewAiAssistTools",
    "useAiChat",
    "openAppSettings",
    "viewLicensingInfo",
  ],
};

const APP_ROLE_PERMISSIONS: AppRolePermissionMap = {
  administrator: [
    "viewProject",
    "viewProjectDashboard",
    "viewProjectMetadata",
    "editProjectMetadata",
    "deleteProject",
    "exportProject",
    "restoreProjectBackup",
    "viewProjectUsers",
    "inviteProjectUsers",
    "removeProjectUsers",
    "changeProjectRoles",
    "transferProjectOwnership",
    "viewDocuments",
    "openDocumentDetails",
    "createDocument",
    "uploadDocument",
    "batchUploadDocuments",
    "importSpreadsheetDocuments",
    "editDocumentMetadata",
    "editDocumentContent",
    "deleteDocument",
    "associateDocumentsWithCases",
    "viewDocumentAttributes",
    "editDocumentAttributes",
    "createDocumentAttributes",
    "deleteDocumentAttributes",
    "viewCases",
    "openCaseDetails",
    "createCase",
    "editCase",
    "deleteCase",
    "linkCaseDocuments",
    "unlinkCaseDocuments",
    "viewCaseAttributes",
    "editCaseAttributes",
    "createCaseAttributes",
    "deleteCaseAttributes",
    "viewCodebook",
    "createCode",
    "editCode",
    "deleteCode",
    "reorganizeCodes",
    "viewCodeDetails",
    "manageCodeAttributes",
    "viewAnnotations",
    "createAnnotations",
    "editAnnotationNotes",
    "deleteAnnotations",
    "recodeAnnotations",
    "bulkCodeAnnotations",
    "viewUncodedText",
    "filterAnnotations",
    "viewMemos",
    "createMemo",
    "editMemo",
    "deleteMemo",
    "associateMemoObjects",
    "viewReports",
    "createReports",
    "editReportConfiguration",
    "deleteReports",
    "exportReports",
    "viewAiAssistHome",
    "viewAiAssistTools",
    "enableProjectAiAssist",
    "buildEmbeddings",
    "deleteEmbeddings",
    "useAiChat",
    "useAiCodingTools",
    "useAiAttributeTools",
    "useAiAnalyzeTools",
    "useAiProcessDocuments",
    "saveAiOutputs",
    "editAiOutputs",
    "exportAiOutputsToProject",
    "deleteAiOutputs",
    "reviewProcessedDocuments",
    "approveProcessedDocuments",
    "openAppSettings",
    "changeStartupSettings",
    "manageLlmSettings",
    "downloadEmbeddingModel",
    "deleteEmbeddingModel",
    "viewLocalUsers",
    "deleteLocalUsers",
    "clearLocalAppData",
    "viewLicensingInfo",
    "bypassReadOnlyProtections",
    "performPermanentDeleteActions",
    "exportSensitiveContent",
    "manageBackupsAndRestores",
  ],
  standard: [
    "openAppSettings",
    "viewLicensingInfo",
  ],
};

export function getProjectRolePermissions(role: Role | null | undefined): readonly Permission[] {
  const normalizedRole = normalizeProjectRole(role);
  if (!normalizedRole) return [];
  return PROJECT_ROLE_PERMISSIONS[normalizedRole];
}

export function getAppRolePermissions(role: AppRole | null | undefined): readonly Permission[] {
  return APP_ROLE_PERMISSIONS[normalizeAppRole(role)];
}

export function hasProjectPermission(role: Role | null | undefined, permission: Permission): boolean {
  return getProjectRolePermissions(role).includes(permission);
}

export function hasAppPermission(role: AppRole | null | undefined, permission: Permission): boolean {
  return getAppRolePermissions(role).includes(permission);
}

export function hasPermission(context: {
  appRole?: AppRole | null;
  projectRole?: Role | null;
  permission: Permission;
}): boolean {
  return (
    hasAppPermission(context.appRole, context.permission)
    || hasProjectPermission(context.projectRole, context.permission)
  );
}

export function listAllPermissions(): readonly Permission[] {
  return PERMISSIONS;
}

export function normalizeProjectRole(role: unknown): Role | null {
  const value = String(role ?? "").trim().toLowerCase();
  if ((VALID_PROJECT_ROLES as readonly string[]).includes(value)) {
    return value as Role;
  }
  return null;
}

export function normalizeAppRole(role: unknown): AppRole {
  const value = String(role ?? "").trim().toLowerCase();
  if ((VALID_APP_ROLES as readonly string[]).includes(value)) {
    return value as AppRole;
  }
  return "standard";
}
