export type PermissionMatrixRow = {
  category: string;
  permission: string;
  description: string;
  administrator: boolean;
  owner: boolean;
  editor: boolean;
  coder: boolean;
  viewer: boolean;
  notes: string;
};

export const permissionMatrixRows: PermissionMatrixRow[] = [
  { category: 'Project Access', permission: 'View project', description: 'Open the project at all', administrator: true, owner: true, editor: true, coder: true, viewer: true, notes: '' },
  { category: 'Project Access', permission: 'View project dashboard/home', description: 'See project overview and summaries', administrator: true, owner: true, editor: true, coder: true, viewer: true, notes: '' },
  { category: 'Project Access', permission: 'View project metadata', description: 'See project name description and settings summary', administrator: true, owner: true, editor: true, coder: true, viewer: true, notes: '' },
  { category: 'Project Access', permission: 'Edit project metadata', description: 'Change project name description and other core metadata', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: '' },
  { category: 'Project Access', permission: 'Delete project', description: 'Permanently delete the project', administrator: true, owner: true, editor: false, coder: false, viewer: false, notes: 'Administrator may need to be added as an override outside normal membership' },
  { category: 'Project Access', permission: 'Export or backup project', description: 'Create project backup or export files', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: '' },
  { category: 'Project Access', permission: 'Restore or import project backup', description: 'Restore a project from a backup or import package', administrator: true, owner: true, editor: false, coder: false, viewer: false, notes: '' },
  { category: 'Project Membership', permission: 'View project users', description: 'See project members and roles', administrator: true, owner: true, editor: true, coder: true, viewer: true, notes: '' },
  { category: 'Project Membership', permission: 'Invite or add users', description: 'Add users to a project', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: '' },
  { category: 'Project Membership', permission: 'Remove users', description: 'Remove users from a project', administrator: true, owner: true, editor: false, coder: false, viewer: false, notes: '' },
  { category: 'Project Membership', permission: 'Change user roles', description: 'Promote or demote project members', administrator: true, owner: true, editor: false, coder: false, viewer: false, notes: '' },
  { category: 'Project Membership', permission: 'Transfer ownership', description: 'Hand project ownership to another member', administrator: true, owner: true, editor: false, coder: false, viewer: false, notes: '' },
  { category: 'Documents', permission: 'View documents list', description: 'See available documents', administrator: true, owner: true, editor: true, coder: true, viewer: true, notes: '' },
  { category: 'Documents', permission: 'Open document details', description: 'Read a document', administrator: true, owner: true, editor: true, coder: true, viewer: true, notes: '' },
  { category: 'Documents', permission: 'Create document manually', description: 'Add a typed document', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: '' },
  { category: 'Documents', permission: 'Upload single document', description: 'Upload one supported file', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: '' },
  { category: 'Documents', permission: 'Batch upload documents', description: 'Upload multiple supported files', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: '' },
  { category: 'Documents', permission: 'Spreadsheet import documents', description: 'Create documents from CSV or XLSX rows', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: '' },
  { category: 'Documents', permission: 'Edit document metadata', description: 'Change document name description or type', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: '' },
  { category: 'Documents', permission: 'Edit document content', description: 'Change the main text content', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: '' },
  { category: 'Documents', permission: 'Delete document', description: 'Remove a document', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: '' },
  { category: 'Documents', permission: 'Associate documents with cases', description: 'Link or unlink documents to cases', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: '' },
  { category: 'Documents', permission: 'View document attributes', description: 'See document attribute values', administrator: true, owner: true, editor: true, coder: true, viewer: true, notes: '' },
  { category: 'Documents', permission: 'Edit document attributes', description: 'Change attribute values on documents', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: '' },
  { category: 'Documents', permission: 'Create document attributes', description: 'Add new document attribute definitions', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: '' },
  { category: 'Documents', permission: 'Delete document attributes', description: 'Remove document attribute definitions or values', administrator: true, owner: true, editor: false, coder: false, viewer: false, notes: '' },
  { category: 'Cases', permission: 'View cases list', description: 'See all cases', administrator: true, owner: true, editor: true, coder: true, viewer: true, notes: '' },
  { category: 'Cases', permission: 'Open case details', description: 'Read a case', administrator: true, owner: true, editor: true, coder: true, viewer: true, notes: '' },
  { category: 'Cases', permission: 'Create case', description: 'Add a new case', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: '' },
  { category: 'Cases', permission: 'Edit case', description: 'Change case name description or other metadata', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: '' },
  { category: 'Cases', permission: 'Delete case', description: 'Remove a case', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: '' },
  { category: 'Cases', permission: 'Link documents to case', description: 'Associate documents with a case', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: '' },
  { category: 'Cases', permission: 'Unlink documents from case', description: 'Remove document associations from a case', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: '' },
  { category: 'Cases', permission: 'View case attributes', description: 'See case attribute values', administrator: true, owner: true, editor: true, coder: true, viewer: true, notes: '' },
  { category: 'Cases', permission: 'Edit case attributes', description: 'Change case attribute values', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: '' },
  { category: 'Cases', permission: 'Create case attributes', description: 'Add new case attribute definitions', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: '' },
  { category: 'Cases', permission: 'Delete case attributes', description: 'Remove case attribute definitions or values', administrator: true, owner: true, editor: false, coder: false, viewer: false, notes: '' },
  { category: 'Codebook and Codes', permission: 'View codebook', description: 'See the list and hierarchy of codes', administrator: true, owner: true, editor: true, coder: true, viewer: true, notes: '' },
  { category: 'Codebook and Codes', permission: 'Create code', description: 'Add a new code', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: '' },
  { category: 'Codebook and Codes', permission: 'Edit code', description: 'Change code name description or color', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: '' },
  { category: 'Codebook and Codes', permission: 'Delete code', description: 'Remove a code', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: '' },
  { category: 'Codebook and Codes', permission: 'View code details', description: 'Open code information', administrator: true, owner: true, editor: true, coder: true, viewer: true, notes: '' },
  { category: 'Codebook and Codes', permission: 'Manage code attributes', description: 'Add edit or remove code metadata if used', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: '' },
  { category: 'Annotations and Coding', permission: 'View annotations', description: 'See coded segments and annotation details', administrator: true, owner: true, editor: true, coder: true, viewer: true, notes: '' },
  { category: 'Annotations and Coding', permission: 'Create annotations', description: 'Apply codes to text', administrator: true, owner: true, editor: true, coder: true, viewer: false, notes: 'Coder should be able to code' },
  { category: 'Annotations and Coding', permission: 'Edit annotation notes', description: 'Change memo or note text on annotations', administrator: true, owner: true, editor: true, coder: true, viewer: false, notes: '' },
  { category: 'Annotations and Coding', permission: 'Delete annotations', description: 'Remove coded segments', administrator: true, owner: true, editor: true, coder: true, viewer: false, notes: '' },
  { category: 'Annotations and Coding', permission: 'View uncoded text', description: 'Read source text during coding', administrator: true, owner: true, editor: true, coder: true, viewer: true, notes: '' },
  { category: 'Annotations and Coding', permission: 'Filter or search annotations', description: 'Use coding filters and search tools', administrator: true, owner: true, editor: true, coder: true, viewer: true, notes: '' },
  { category: 'Memos', permission: 'View memos', description: 'See memo list and details', administrator: true, owner: true, editor: true, coder: true, viewer: true, notes: '' },
  { category: 'Memos', permission: 'Create memo', description: 'Add a memo', administrator: true, owner: true, editor: true, coder: true, viewer: false, notes: 'Coders often need analytic memos' },
  { category: 'Memos', permission: 'Edit memo', description: 'Change memo title or contents', administrator: true, owner: true, editor: true, coder: true, viewer: false, notes: '' },
  { category: 'Memos', permission: 'Delete memo', description: 'Remove a memo', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: '' },
  { category: 'Memos', permission: 'Associate memo with objects', description: 'Link a memo to documents cases codes or annotations', administrator: true, owner: true, editor: true, coder: true, viewer: false, notes: '' },
  { category: 'Reports', permission: 'View reports pages', description: 'Open the reports area', administrator: true, owner: true, editor: true, coder: true, viewer: true, notes: '' },
  { category: 'Reports', permission: 'Create reports', description: 'Start a new report', administrator: true, owner: true, editor: true, coder: true, viewer: false, notes: 'Coders may need working reports' },
  { category: 'Reports', permission: 'Edit report configuration', description: 'Change report filters sorts columns or options', administrator: true, owner: true, editor: true, coder: true, viewer: false, notes: '' },
  { category: 'Reports', permission: 'Delete reports', description: 'Remove saved reports', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: '' },
  { category: 'Reports', permission: 'Export reports', description: 'Export reports to HTML PDF DOCX or similar', administrator: true, owner: true, editor: true, coder: true, viewer: false, notes: '' },
  { category: 'AI Assist General', permission: 'View AI Assist home', description: 'Open AI Assist status and home screen', administrator: true, owner: true, editor: true, coder: true, viewer: true, notes: '' },
  { category: 'AI Assist General', permission: 'View AI Assist tools', description: 'See AI Assist tools beyond home', administrator: true, owner: true, editor: true, coder: true, viewer: true, notes: 'Can also be conditioned on project AI Assist being enabled' },
  { category: 'AI Assist General', permission: 'Enable AI Assist for project', description: 'Turn project AI Assist on or off', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: '' },
  { category: 'AI Assist General', permission: 'Build embeddings', description: 'Start project embedding generation', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: '' },
  { category: 'AI Assist General', permission: 'Delete embeddings', description: 'Remove project embeddings', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: '' },
  { category: 'AI Assist General', permission: 'Use AI chat', description: 'Ask project grounded AI questions', administrator: true, owner: true, editor: true, coder: true, viewer: true, notes: '' },
  { category: 'AI Assist General', permission: 'Use AI coding tools', description: 'Use AI assisted coding workflows', administrator: true, owner: true, editor: true, coder: true, viewer: false, notes: '' },
  { category: 'AI Assist General', permission: 'Use AI attribute tools', description: 'Use AI attribute identification workflows', administrator: true, owner: true, editor: true, coder: true, viewer: false, notes: '' },
  { category: 'AI Assist General', permission: 'Use AI analyze tools', description: 'Use AI analysis outputs and prompts', administrator: true, owner: true, editor: true, coder: true, viewer: false, notes: '' },
  { category: 'AI Assist General', permission: 'Use AI process documents', description: 'Use transcript or document processing workflows', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: 'This may be limited to stronger roles because it creates new project assets' },
  { category: 'AI Assist Outputs', permission: 'Save AI generated outputs', description: 'Persist generated results or review changes', administrator: true, owner: true, editor: true, coder: true, viewer: false, notes: '' },
  { category: 'AI Assist Outputs', permission: 'Edit AI generated outputs', description: 'Modify reviewed AI outputs before saving', administrator: true, owner: true, editor: true, coder: true, viewer: false, notes: '' },
  { category: 'AI Assist Outputs', permission: 'Export AI generated outputs to project', description: 'Turn processed outputs into project documents or data', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: '' },
  { category: 'AI Assist Outputs', permission: 'Delete AI generated outputs', description: 'Remove generated or review items', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: '' },
  { category: 'AI Assist Outputs', permission: 'Review processed documents', description: 'Open the processed document review queue', administrator: true, owner: true, editor: true, coder: true, viewer: false, notes: '' },
  { category: 'AI Assist Outputs', permission: 'Approve processed documents', description: 'Mark processed outputs as accepted for project use', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: '' },
  { category: 'Application and Device Administration', permission: 'Open App Settings', description: 'Access app level settings pages', administrator: true, owner: true, editor: true, coder: true, viewer: true, notes: 'Some subsections can still be role limited' },
  { category: 'Application and Device Administration', permission: 'Change startup or session settings', description: 'Modify app startup and session behavior', administrator: true, owner: false, editor: false, coder: false, viewer: false, notes: 'Device level behavior should stay admin only' },
  { category: 'Application and Device Administration', permission: 'Manage LLM connection settings', description: 'Edit Ollama or local model connection settings', administrator: true, owner: false, editor: false, coder: false, viewer: false, notes: '' },
  { category: 'Application and Device Administration', permission: 'Download embedding model', description: 'Download model files to the device', administrator: true, owner: false, editor: false, coder: false, viewer: false, notes: '' },
  { category: 'Application and Device Administration', permission: 'Delete embedding model', description: 'Remove model files from the device', administrator: true, owner: false, editor: false, coder: false, viewer: false, notes: '' },
  { category: 'Application and Device Administration', permission: 'View local users', description: 'See registered local users on the device', administrator: true, owner: false, editor: false, coder: false, viewer: false, notes: '' },
  { category: 'Application and Device Administration', permission: 'Delete local users', description: 'Remove local users from the device', administrator: true, owner: false, editor: false, coder: false, viewer: false, notes: '' },
  { category: 'Application and Device Administration', permission: 'Clear local app data', description: 'Wipe app data cache or storage on the device', administrator: true, owner: false, editor: false, coder: false, viewer: false, notes: '' },
  { category: 'Application and Device Administration', permission: 'View licensing and about info', description: 'Open release license and about information', administrator: true, owner: true, editor: true, coder: true, viewer: true, notes: '' },
  { category: 'System and Safety', permission: 'Bypass read only protections', description: 'Perform actions reserved from read only roles', administrator: true, owner: true, editor: false, coder: false, viewer: false, notes: '' },
  { category: 'System and Safety', permission: 'Perform permanent delete actions', description: 'Execute irreversible deletion flows', administrator: true, owner: true, editor: true, coder: false, viewer: false, notes: '' },
  { category: 'System and Safety', permission: 'Export sensitive content', description: 'Export project content outside the app', administrator: true, owner: true, editor: true, coder: true, viewer: false, notes: '' },
  { category: 'System and Safety', permission: 'Manage backups and restores', description: 'Control backup creation and restore operations', administrator: true, owner: true, editor: false, coder: false, viewer: false, notes: '' },
];
